### ISSUE TITLE
FUConfig - Routers getting stuck assigned

### ISSUE THREAD

**Issue by dalez0r** [fu-telecom/fu-telecom#5]
# Overview
When you remove an org, if you have not removed any routers associated with that org, that router gets 'stuck' assigned to that org and unavailable to assign to a different org.  

# Steps to reproduce
1. On home, scroll to an org that's already had it's phones removed but still has a router
2. click 'remove' on the gray bar with org's name
3. scroll to a different org, click 'add router'
4. notice that that router is marked "already assigned" and still shows the previous org's name under notes and location.

# Expected behavior
Either router is removed automatically when org is removed, or an error message stopping you is given.

# Actual behavior
Org is removed, router no longer shows on main page, but is unavailable to add elsewhere.  

# Impact
Has to be manually fixed in teh database outside FUConfig by a knowledged tech. Time consuming of the techs who know how. Problematic if tech is unavailable.

# Additional details
@_@

**Comment by veliebm** [comment]
I was able to reproduce this bug using router 65 and a test org I made.

![image](https://github.com/spencerflem/fu-telecom/assets/67563877/ef100440-8308-4c30-9dd0-01e28be292ea)

**Comment by veliebm** [comment]
I think I've found the area of code [where deleting organizations is handled](https://github.com/spencerflem/fu-telecom/blob/6593b67545b206fef695989774a91e97b8c7bf16/fuconfig/orgs-update.php#L14-L36). It already stops users from [deleting organizations with assigned phones](https://github.com/spencerflem/fu-telecom/blob/6593b67545b206fef695989774a91e97b8c7bf16/fuconfig/orgs-update.php#L29-L36). We should add a check to stop users from deleting organizations with assigned routers.
